export const SELECTED_WORD = 'SELECTED_WORD';
export const WORDS_SUCCESS = 'WORDS_SUCCESS';
export const SEARCH_WORD_REQUEST = 'SEARCH_WORD_REQUEST';
export const SEARCH_WORD_SUCCESS = 'SEARCH_WORD_SUCCESS';
export const SEARCH_WORD_FAILURE = 'SEARCH_WORD_FAILURE';
