const events = {
  INSTALLED: 'INSTALLED',
  INSTALL_REJECTED: 'INSTALL_REJECTED',
  SEARCH_WORD: 'SEARCH_WORD',
  BOOKMARK_WORD: 'BOOKMARK_WORD',
  SEARCH_WORD_ON_WEB: 'SEARCH_WORD_ON_WEB',
  REMOVE_BOOKMARKED_WORD: 'REMOVE_BOOKMARKED_WORD',
  COPY_WORD: 'COPY_WORD',
  SHARE_WORD: 'SHARE_WORD',
  SETTINGS_PAGE: 'SETTINGS_PAGE',
  ADD_WORD_PAGE: 'ADD_WORD_PAGE',
  HOME_PAGE: 'HOME_PAGE'
};

export default events;
