const events = {
  // pages
  SETTINGS_PAGE: 'SETTINGS_PAGE',
  HOME_PAGE: 'HOME_PAGE',
  // apps
  INSTALLED: 'INSTALLED',
  INSTALL_REJECTED: 'INSTALL_REJECTED',
  SHARE_APP: 'SHARE_APP',
  SHARE_APP_FAILED: 'SHARE_APP_FAILED',
  COPIED_APP_LINK: 'COPIED_APP_LINK',
  // user
  USER_REGISTRATION: 'USER_REGISTRATION',
  USER_LOG_OUT: 'USER_LOG_OUT',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  TOGGLE_QUIZ_MODE: 'TOGGLE_QUIZ_MODE',
  // words
  SEARCH_WORD: 'SEARCH_WORD',
  BOOKMARK_WORD: 'BOOKMARK_WORD',
  SEARCH_WORD_ON_WEB: 'SEARCH_WORD_ON_WEB',
  REMOVE_BOOKMARKED_WORD: 'REMOVE_BOOKMARKED_WORD',
  COPY_WORD: 'COPY_WORD',
  SHARE_WORD: 'SHARE_WORD',
  FIND_SYNONYM: 'FIND_SYNONYM',
  // global error
  APP_CRASHED: 'APP_CRASHED'
};

export default events;
